version: "2"

services:

  mysqldb:
    container_name: mysqldb_container
    image: blbsystem/mysql:5.7
    build: .
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=blbsyst3m
      - MYSQL_USER=userdb
      - MYSQL_PASSWORD=blbuserdbprod
      - MYSQL_DATABASE=user
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - mysql-tier

networks:
  mysql-tier:
    driver: bridge

volumes:
  mysql-storage:
    driver: local